query GetAllGroups {
  groups {
    data {
      id
      attributes {
        name
        vidilenya {
          data {
            attributes {
              name
            }
          }
        }
        specialty
        educationalDegree
        course_number
      }
    }
  }
}
