query GetAllVidilenyas {
  vidilenyas {
    data {
      id
      attributes {
        name
        slug
        main_photo {
          data {
            attributes {
              url
              width
              height
            }
          }
        }
      }
    }
  }
}
