query GetAllEvents {
  events(pagination: { pageSize: 100 }) {
    data {
      id
      attributes {
        title
        date
        image {
          data {
            attributes {
              name
              url
              width
              height
            }
          }
        }
      }
    }
  }
}
