query GetFamousGraduates {
  famousGraduates(pagination: { pageSize: 100 }) {
    data {
      id
      attributes {
        name
        photo {
          data {
            attributes {
              name
              width
              height
              url
            }
          }
        }
        description
      }
    }
  }
}
