query GetNews($currentPage: Int = 1, $pageSize: Int = 3) {
  novinas(sort: "date:desc", pagination: { page: $currentPage, pageSize: $pageSize }) {
    meta {
      pagination {
        total
        page
        pageSize
        pageCount
      }
    }

    data {
      id
      attributes {
        title
        body

        main_photo {
          data {
            attributes {
              width
              height
              url
            }
          }
        }

        collage_photo {
          data {
            attributes {
              width
              height
              url
            }
          }
        }

        date
        video_url
      }
    }
  }
}
